name: Bug
description: Report a bug
title: "[Bug]: "
labels: ["bug"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        ## Description

        Describe the issue in detail.
  - type: input
    id: bug-name
    attributes:
      label: Bug Name
      description: A short name for the bug
      placeholder: "Describe the bug in a few words"
    validations:
      required: true
  - type: textarea
    id: bug-behaviour
    attributes:
      label: Bug Behaviour
      description: Describe the bug behaviour
      placeholder: "Describe the bug behaviour"
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: Describe the expected behaviour
      placeholder: "Describe the expected behaviour"
    validations:
      required: true
