name: Task
description: Report a task
title: "[Task]: "
labels: ["task"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        ## Description

        Describe the issue in detail.
  - type: input
    id: task-name
    attributes:
      label:  Task Name
      description: A short name for the task
      placeholder: "Describe the task in a few words"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Describe the steps to reproduce the issue
      placeholder: "Steps to reproduce the issue"
    validations:
      required: true